### ISSUE TITLE
Support for React Hooks API

### ISSUE THREAD

**Issue by arx-8** [joeattardi/react-snackbar-alert#5]
Thank you for creating an awesome package!
I think this package is excellent for both UX and DX (Developer eXperience).
I was looking for this!

And, I have one suggestion.
Please support for Hooks.

## Code

Only 4 lines are needed, as follows:

```js
import { useContext } from "react";
import { SnackbarContext } from "react-snackbar-alert";

export const useSnackbar = () => useContext(SnackbarContext);
```

### Example

https://codesandbox.io/s/flamboyant-lovelace-gd8x2

---

Thank you for your consideration!

**Comment by joeattardi** [comment]
I am actually going to be deprecating this package as it has just not gotten any popularity and as such it's not worth the time to maintain it.

**Comment by arx-8** [comment]
Thank you for your reply.
I am very sad ... :cry:
