### ISSUE TITLE
Do you plan to support TypeScript?

### ISSUE THREAD

**Issue by arx-8** [joeattardi/react-snackbar-alert#6]
Do you plan to support TypeScript?
If not, May I contribute to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by joeattardi** [comment]
I am actually going to be deprecating this package as it has just not gotten any popularity and as such it's not worth the time to maintain it.

**Comment by arx-8** [comment]
Ok, I understand. :cry:  

Instead, I leave definition in my gist.
For someone who loves your package.

https://gist.github.com/arx-8/7a03b68d395c31ac486a133c5eb7842f
